services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - portainer
      - homeassistant
    networks:
      digit_isolated:
      digit_docker_network:
        ipv4_address: 172.1.0.200

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - digit_docker_network

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host

  qbittorent:
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - 8080:8080
      - 49500:49500
      - 49500:49500/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=49500
    volumes:
      - ./qbittorrent/appdata:/config
      - ./qbittorrent/downloads:/downloads
    networks:
      - digit_vpn_vlan
      - digit_isolated
  jellyfin:
    image: jellyfin/jellyfin
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: /home/roqueo/media/movies
        target: /media
      #- type: bind
      #  source: /path/to/media2
      #  target: /media2
      #  read_only: true
    restart: 'unless-stopped'
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway' 

volumes:
  portainer_data:

networks:
  digit_docker_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24

  digit_vpn_vlan:
    driver: macvlan
    driver_opts:
      parent: eno1.20
    ipam:
      config:
        - subnet: 192.168.3.0/24
          ip_range: 192.168.3.96/30
          gateway: 192.168.3.1

  digit_isolated:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/24